name: liaz
description: "LIAZ"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  get: ^4.6.6
  remixicon: ^1.0.0
  easy_refresh: ^3.3.2+4
  flutter_smart_dialog: ^4.9.5+1
  lottie: ^2.7.0
  flutter_swiper_view: ^1.1.8
  extended_image: ^8.2.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
