name: liaz
description: "LIAZ"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  get: ^4.6.6
  remixicon: ^1.0.0
  easy_refresh: ^3.3.2+4
  flutter_smart_dialog: ^4.9.5+1
  lottie: ^2.7.0
  flutter_swiper_view: ^1.1.8
  extended_image: ^8.2.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  flutter_speed_dial: ^7.0.0
  dio: ^5.4.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  uuid: ^4.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  connectivity_plus: ^5.0.2
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  crypto: ^3.0.3
  convert: ^3.1.1
  preload_page_view: ^0.2.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
